25 feat sign in page markup
GEOFARL/online-dictionary pull request #55
Opened 2024-03-26 09:57 UTC by kovalsofiia1

2024-03-26 10:29 UTC, GEOFARL requested changes

2024-03-26 10:29 UTC, GEOFARL commented on package.json
> +		"@types/bcrypt": "^5.0.2",
It should be a devDependency

2024-03-26 10:29 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +    <script src="/js/toggle-password.js"></script>
You should write create this function inside of the `client/src/shared/helpers` folder, use it in the `sign-in.ts` file

2024-03-26 10:29 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +    <script src="/js/toggle-password.js"></script>
js files are produced in the result of the compilation process and they're ignored, so you even has not commited it

2024-03-26 10:29 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +
```suggestion
```

2024-03-26 10:29 UTC, GEOFARL commented on src/views/components/password-input.ejs
> +    <button class="toggle-password-btn" id="togglePassword">
include type="button", now it submits a form

2024-03-26 10:29 UTC, GEOFARL commented on src/views/components/password-input.ejs
> +  </div>
do not create a separate component for it

2024-03-26 10:29 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +          <a href="/sign-up" class="register-text">Зареєструватися</a>
create a link component

2024-03-26 10:29 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +        <h1 class="sign-in-title">З поверненням!</h1>
```suggestion
        <div class="welcome-container">
        <h2 class="heading">З поверненням!</h1>
```
remove sign-in part everywhere, as it's already sign in page and we're using specific sign-in styles

2024-03-26 10:29 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +        </div>
```suggestion
        <div class="prompt">
          <p class="prompt__question">Немає акаунту?</p>
          <a href="/sign-up" class="prompt__link">Зареєструватися</a>
        </div>
```

2024-03-26 10:29 UTC, GEOFARL commented on src/views/components/button.ejs
> +><%= label %></button>
unnecessary change

2024-03-26 10:29 UTC, GEOFARL commented on src/client/public/css/pages/sign-in.css
> +.register-container {
keep the spacing consistent

2024-03-26 10:33 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +        </div>
```suggestion
        <div class="sign-in-welcome-container">
        <h1 class="sign-in-title">З поверненням!</h1>
        <div class="register-container">
          <p class="sign-in-text">Немає акаунту?</p>
          <a href="/sign-up" class="register-text">Зареєструватися</a>
        </div>
```

keep indentation levels

2024-03-26 10:35 UTC, GEOFARL commented
Also, add button hover, active and focus states

2024-03-27 16:25 UTC, GEOFARL requested changes

2024-03-27 16:25 UTC, GEOFARL commented on package.json
> +		"@types/bcrypt": "^5.0.2",
it is still in dependencies, not resolved

2024-03-27 16:25 UTC, GEOFARL commented on src/client/src/pages/sign-in/sign-in.ts
> +import { initPasswordToggle } from "../../../public/shared/helpers/password-toggle";
```suggestion
import { initPasswordToggle } from "~/shared/index.js";
```

2024-03-27 16:25 UTC, GEOFARL commented on src/client/src/pages/sign-in/sign-in.ts
> +import { initPasswordToggle } from "../../../public/shared/helpers/password-toggle";
<img width="737" alt="image" src="https://github.com/GEOFARL/online-dictionary/assets/110524091/5f94c60c-f5c0-4b13-a7ed-9f9250c19ea7">

2024-03-27 16:25 UTC, GEOFARL commented on src/client/public/shared/helpers/password-toggle.ts
> +export function initPasswordToggle() {
```suggestion
const initPasswordToggle = () => {
```

2024-03-27 16:25 UTC, GEOFARL commented on src/client/public/shared/helpers/password-toggle.ts
> +}
```suggestion
}

export { initPasswordToggle };
```

2024-03-27 16:25 UTC, GEOFARL commented on src/views/components/link.ejs
> +<a href="<%= href %>" class="<%= linkClass %>"><%= text %></a>
It would throw errors, if we do not include link class, make it optional

2024-03-27 16:25 UTC, GEOFARL commented on src/views/components/link.ejs
> +<a href="<%= href %>" class="<%= linkClass %>"><%= text %></a>
```suggestion
<a href="<%= href %>" class="<%= className %>"><%= content %></a>
```

2024-03-27 16:25 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +
```suggestion
```

2024-03-27 16:25 UTC, GEOFARL commented on package.json
> +		"@types/bcrypt": "^5.0.2",
btw, why do you need at all?

2024-03-27 16:25 UTC, GEOFARL commented on src/client/public/css/pages/sign-in.css
> +	height: 24px;
<img width="771" alt="image" src="https://github.com/GEOFARL/online-dictionary/assets/110524091/381a1237-e171-4b98-ac4e-e94f2f2c2cf2">

remove extra spacing between form controls, extra paddings, etc make it look as in design

2024-03-27 16:25 UTC, GEOFARL commented on src/client/public/css/components/button.css
> +}
add transition and pointer cursor

2024-03-27 16:25 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +              <hr>
style this separators as in design

2024-03-27 16:25 UTC, GEOFARL commented on src/client/public/shared/helpers/password-toggle.ts
> +}
use dom module that we have in `/client/src/shared/libs/modules/dom/dom.ts`, add a new method to it for changing attributes of DOM elements

2024-03-28 10:52 UTC, kovalsofiia1 commented
![Знімок екрана 2024-03-28 124915](https://github.com/GEOFARL/online-dictionary/assets/116633872/660ad46a-6bb6-4e6d-bb55-724cd98da951)

2024-03-28 12:34 UTC, GEOFARL requested changes

2024-03-28 12:34 UTC, GEOFARL commented on src/client/public/css/components/button.css
> +	transition: all 0.6s ease-in-out;
```suggestion
 transition: all 0.2s ease-in-out;
    border: 2px solid transparent;
```

2024-03-28 12:34 UTC, GEOFARL commented on src/client/public/css/components/input.css
> +	border-color: var(--color-grey-300);
```suggestion
	border-color: var(--color-grey-300);
  background-color: rgba(175 175 175 /15%);
```

let's add here backgroun change as well

2024-03-28 12:34 UTC, GEOFARL commented on src/client/public/css/pages/sign-in.css
> +}
will make a separate component out of it as well

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/pages/sign-in/sign-in.ts
> +import { initPasswordToggle } from "~/shared/helpers/password-toggle";
```suggestion
import { initPasswordToggle } from "~/shared/index.js";
```

create a file `helpers.ts`, reexport that function from there and then reexport it inside of the `shared/index.ts` from `./libs/helpers/helpers.js`

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +const initPasswordToggle = () => {
file name should match the name of the function
rename it to the init-password-toggle.ts

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +import { dom } from "../libs/modules/dom/dom";
```suggestion
import { dom } from "../libs/modules/dom/dom.js";
```

include js extension in all of the imports

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +		dom.changeAttribute("#password", "type", type);
```suggestion
```

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +	const togglePasswordBtn = dom.getElement("#togglePassword");
```suggestion
```

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +			passwordInput.getAttribute("type") === "password" ? "text" : "password";
```suggestion
		const type =
			dom.getAttribute({
				attribute: "type",
				selector: "#password",
			}) === "password"
				? "text"
				: "password";
```

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +	togglePasswordBtn.addEventListener("click", () => {
```suggestion
	 dom.setListener({
    selector: '#toggle-password',
    eventType: 'click',
    listener: () => {}
  })
```

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/helpers/password-toggle.ts
> +			);
```suggestion
			dom.changeAttribute({
				selector: ".show-password-icon",
				type: "src",
				value: "/icons/eye-closed.svg",
			});
```

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/libs/modules/dom/base-dom.module.ts
> +	changeAttribute(selector: string, attribute: string, value: string): void {
should be similar to setListener method

2024-03-28 12:34 UTC, GEOFARL commented on src/client/src/shared/libs/modules/dom/base-dom.module.ts
> +		}
reuse existing methods of the class (getElement)

2024-03-28 12:34 UTC, GEOFARL commented on src/views/components/link.ejs
> +<a href="<%= href %>"<% if (typeof className !== 'undefined') { %> class="<%= className %>"<% } %>><%= content %></a>
```suggestion
<a href="<%- href %>" class="link <%- locals.className ? className : '' %>"><%- content %></a>
```
add default link styles inside of the link.css file

2024-03-28 12:34 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +        <hr class="separator">
make a component out of it

2024-03-28 12:34 UTC, GEOFARL commented on src/views/pages/sign-in.ejs
> +                    <button class="toggle-password-btn" id="togglePassword" type="button">
```suggestion
                    <button class="toggle-password-btn" id="toggle-password" type="button">
```

2024-03-28 12:39 UTC, GEOFARL commented
@kovalsofiia1, do not include 'fix' when creating a fix commit in the message after :

2024-03-28 17:16 UTC, GEOFARL approved these changes

2024-03-28 17:17 UTC, merged